version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 32000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=password

  app:
    build: .
    ports:
     - "5000:5000"
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "-t", "120" , "--", "python", "feature_request.py", "docker"]
