version: '2'
services:
  app:
    build: .
    ports:
     - "5000:5000"
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 32000:3306
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_DATABASE="testdb"
      - MYSQL_USER="test"
      - MYSQL_PASSWORD="testing"


